-- Table des utilisateurs (Nyé-F1 auth, Nyé-F7 profil, Nyé-F5 notifications).
-- Types choisis pour rester compatibles à l'identique entre H2 (dev) et PostgreSQL (prod) :
-- IDENTITY (ANSI SQL) plutôt que SERIAL/AUTO_INCREMENT, TIMESTAMP WITH TIME ZONE pour les Instant.
CREATE TABLE users (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name                 VARCHAR(255) NOT NULL,
    phone                     VARCHAR(255) NOT NULL,
    email                     VARCHAR(255),
    password_hash             VARCHAR(255) NOT NULL,
    role                      VARCHAR(255) NOT NULL,
    language                  VARCHAR(255) NOT NULL,
    enabled                   BOOLEAN NOT NULL DEFAULT TRUE,
    phone_verified            BOOLEAN NOT NULL DEFAULT FALSE,
    otp_code                  VARCHAR(255),
    otp_expires_at            TIMESTAMP WITH TIME ZONE,
    fcm_token                 VARCHAR(255),
    notifications_enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    notification_radius_km    DOUBLE PRECISION NOT NULL DEFAULT 10.0,
    last_known_latitude       DOUBLE PRECISION,
    last_known_longitude      DOUBLE PRECISION,
    last_location_updated_at  TIMESTAMP WITH TIME ZONE,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_users_phone UNIQUE (phone)
);
