-- Table des alertes de disparition (Nyé-F2 à F6, Nyé-A1/A2). Cycle de vie :
-- PENDING -> ACTIVE (validée par un admin) -> RESOLVED (clôturée avec une note).
CREATE TABLE alerts (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    missing_person_name         VARCHAR(255) NOT NULL,
    missing_person_age          INTEGER,
    missing_person_is_minor     BOOLEAN NOT NULL DEFAULT FALSE,
    description                 VARCHAR(2000) NOT NULL,
    photo_url                   VARCHAR(255) NOT NULL,
    contact_phone               VARCHAR(255) NOT NULL,
    latitude                    DOUBLE PRECISION NOT NULL,
    longitude                   DOUBLE PRECISION NOT NULL,
    address                     VARCHAR(255),
    status                      VARCHAR(255) NOT NULL,
    created_by                  BIGINT NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL,
    validated_at                TIMESTAMP WITH TIME ZONE,
    resolved_at                 TIMESTAMP WITH TIME ZONE,
    resolution_note             VARCHAR(1000),

    CONSTRAINT fk_alerts_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alerts_created_by ON alerts (created_by);
